language: android
sudo: false
jdk:
  - oraclejdk8
#env:
#  global:
#    # wait up to 10 minutes for adb to connect to emulator
#    - ADB_INSTALL_TIMEOUT=10
#    - DEPLOY_USERNAME=travis-android-thekey
#    - DEPLOY_PASSWORD=
#  matrix:
#    - ANDROID_TARGET=android-15 ANDROID_ABI=armeabi-v7a
#    - ANDROID_TARGET=android-21 ANDROID_ABI=armeabi-v7a
#    - ANDROID_TARGET=android-23 ANDROID_ABI=armeabi-v7a
#    - ANDROID_TARGET=android-24 ANDROID_ABI=armeabi-v7a DEPLOY_SNAPSHOT=true
branches:
  only:
    - master

android:
  components:
    - tools
    - tools
    - platform-tools
    - android-27

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches
    - $HOME/.gradle/daemon
    - $HOME/.gradle/native
    - $HOME/.gradle/wrapper

before_script:
  # Install SDK license so Android Gradle plugin can install deps.
  - mkdir -p ${ANDROID_HOME}licenses
  - echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> "$ANDROID_HOME/licenses/android-sdk-license"

# gradle options
#  --parallel      : build/test multiple subprojects simultaneously
#  --continue      : continue processing on an error to try and capture all errors
#  --stacktrace    : output stacktraces for failures to aid in debugging
#  -PdisablePreDex : disable library pre-dex to improve build server performance
script:
  - ./gradlew build -PdisablePreDex --parallel --continue --stacktrace

after_failure:
  - cat /home/travis/build/GlobalTechnology/android-thekey/*/build/outputs/lint-results.xml

#before_deploy:
#  - echo gcxMavenRepositoryUsername=$DEPLOY_USERNAME >> $HOME/.gradle/gradle.properties
#  - echo gcxMavenRepositoryPassword=$DEPLOY_PASSWORD >> $HOME/.gradle/gradle.properties
#
#deploy:
#  provider: script
#  skip_cleanup: true
#  script: ./gradlew uploadArchives --parallel
#  on:
#    repo: GlobalTechnology/android-thekey
#    branch: master
#    jdk: oraclejdk8
#    condition: $DEPLOY_SNAPSHOT = true

notifications:
  email: false
