language: android
sudo: false
jdk:
  - oraclejdk8
env:
  global:
    - DEPLOY_USERNAME=travis-ci-android-thekey
    - secure: aLfXbQByDdqNcOzuzH1EqMQVuaNOQKFqsGROMc2Vo3yShAYsVcn4bB5sQithXAFvVVcAM6Os2IG9cU7oum5fzpSmmmxrlM+kSdQlonWwPlUEt2J+/lHyMBIRznyYLjcAT9V6rMfvJqPi4OohFtPAUKKYbSGj4yj14aqc0+EWY3Q=
    - DEPLOY_SNAPSHOT=true
#  matrix:
#    - ANDROID_TARGET=android-15 ANDROID_ABI=armeabi-v7a
#    - ANDROID_TARGET=android-21 ANDROID_ABI=armeabi-v7a
#    - ANDROID_TARGET=android-23 ANDROID_ABI=armeabi-v7a
#    - ANDROID_TARGET=android-24 ANDROID_ABI=armeabi-v7a DEPLOY_SNAPSHOT=true
branches:
  only:
    - master

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.android/build-cache
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  # Install SDK license so Android Gradle plugin can install deps.
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> "$ANDROID_HOME/licenses/android-sdk-license"
  # Install the rest of tools (e.g., avdmanager)
  - sdkmanager tools

# gradle options
#  --parallel      : build/test multiple subprojects simultaneously
#  --continue      : continue processing on an error to try and capture all errors
#  --stacktrace    : output stacktraces for failures to aid in debugging
#  -PdisablePreDex : disable library pre-dex to improve build server performance
install:
  - ./gradlew clean assemble --continue --stacktrace --parallel

script:
  - ./gradlew check --continue --stacktrace --max-workers 2 --parallel

after_failure:
  - cat /home/travis/build/CruGlobal/android-thekey/*/build/outputs/lint-results.xml

before_deploy:
  - echo cruGlobalMavenRepositoryUsername=$DEPLOY_USERNAME >> $HOME/.gradle/gradle.properties
  - echo cruGlobalMavenRepositoryPassword=$DEPLOY_PASSWORD >> $HOME/.gradle/gradle.properties

deploy:
  provider: script
  skip_cleanup: true
  script: ./gradlew publish --parallel
  on:
    repo: CruGlobal/android-thekey
    branch: master
    jdk: oraclejdk8
    condition: $DEPLOY_SNAPSHOT = true

notifications:
  email: false
